esphome:
  includes:  
    - Air_Quality_v1.h
  libraries:
  - https://github.com/Seeed-Studio/Grove_Air_quality_Sensor.git
  name: esphome-web-c11e75
   

esp8266:
  board: esp01_1m
# Example configuration entry
logger:
  level: DEBUG 
# Enable Home Assistant API
api:
  encryption:
    key: "QRr84gxnQvmEplLCXxoGWmEcSMd9QfYg7nhj/vxQAFA="

ota:
  password: "3bb0ed70401f6592091b286a829d7987"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ivypots Fallback Hotspot"
    password: "heGuP5Rsk3H4"
    
sensor:
  - platform: aht10
    temperature:
      name: "PSalon Temperature"
      accuracy_decimals: 1
    humidity:
      name: "PSalon Humidite"
      accuracy_decimals: 1
    update_interval: 30s
    address: 0x38
    i2c_id: bus_b

  - platform: custom
    lambda: |-
      auto my_sensor = new Air_Quality_v1();
      App.register_component(my_sensor);
      return {my_sensor->Co2};
    sensors:
      name: "Polutions"    
      unit_of_measurement: PPM
      accuracy_decimals: 2  
      
captive_portal:
i2c:
  - id: bus_b
    sda: 4
    scl: 5
    scan: True
